<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <PropertyGroup>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishReadyToRunComposite>false</PublishReadyToRunComposite>
        <StartupObject>LightBoard.App.Program</StartupObject>
        <WarningLevel>8</WarningLevel>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)==Debug">
        <DebugType>full</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)==Release">
        <DebugType>none</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="Properties\" />
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="LightBoard.Tests" />
        <InternalsVisibleTo Include="InkCanvasNext.Tests"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NetOfficeFw.PowerPoint" Version="1.9.11" />
        <PackageReference Include="NetOfficeFw.Word" Version="1.9.11" />
        <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
        <PackageReference Include="PDFiumCore" Version="154.0.8035" />
        <PackageReference Include="SingleInstanceCore" Version="2.2.2" />
    </ItemGroup>
</Project>
