<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net6.0-windows;net9.0-windows</TargetFrameworks>
        <OutputType>WinExe</OutputType>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
    <PropertyGroup>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishReadyToRunComposite>false</PublishReadyToRunComposite>
        <StartupObject>LightBoard.App.Program</StartupObject>
        <WarningLevel>8</WarningLevel>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)==Debug">
        <DebugType>full</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition="$(Configuration)==Release">
        <DebugType>none</DebugType>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="Properties\" />
        <None Include="..\LICENSE">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
        <PackageReference Include="SingleInstanceCore" Version="2.2.2" />
        <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="34.2.4" />
        <PackageReference Include="Syncfusion.PresentationRenderer.Net.Core" Version="34.2.4" />
    </ItemGroup>
</Project>
