name: Build

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x

      - name: Publish App
        run: |
          dotnet publish -p:PublishProfile=FolderProfile -f net6.0-windows -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: LightBoard
          path: ./LightBoard/bin/publish/*

      - name: Publish App with Runtime
        run: |
          dotnet publish -p:PublishProfile=FolderProfile -f net6.0-windows -c Release --self-contained -p:EnableCompressionInSingleFile=true /p:IncludeAllContentForSelfExtract=true

      - name: Upload Artifacts with Runtime
        uses: actions/upload-artifact@v7
        with:
          name: LightBoard-with-runtime
          path: ./LightBoard/bin/publish/*
